framework:
    cache:
        app: 'cache.adapter.redis'
        default_redis_provider: 'redis://localhost'

    messenger:
        transports:
            cache_redis:
                dsn: 'redis://localhost:6379/messages'
                options:
                    stream: 'matachmaking_stream'
                    group: 'matchmaking_group'
                    delete_after_ack: false
                    delete_after_reject: false

        routing:
            App\Message\RedisStreamMessage: cache_redis
